StudentRegistration.Web/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudentRegistration.Web.Models;

namespace StudentRegistration.Web.Controllers
{
    public class CoursesController : Controller
    {
        IStorageService svc;
        public CoursesController(IStorageService _svc)
        {
            svc = _svc;
        }

        public IActionResult Index()
        {
           
            var model = new CoursesHomeModel();
            model.Courses = svc.GetAll();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([FromForm]CourseModel courseModel)
        {
            if (!this.ModelState.IsValid)
            {
                return BadRequest();
            }
            svc.Create(courseModel);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var courseModel = svc.Get(id);

            return View(courseModel);
        }
        [HttpPost]
        public IActionResult Edit(int id,[FromForm]CourseModel courseModel)
        {
            courseModel.Id = id;
            svc.Update(courseModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            svc.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

StudentRegistration.Web/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using StudentRegistration.Web.Entities;
using StudentRegistration.Web.Models;
using StudentRegistration.Web.Services;
using System.Linq;
using System.Threading.Tasks;

namespace StudentRegistration.Web.Controllers
{
    public class StudentsController : Controller
    {
        private readonly StudentsService _studentsService;
        private readonly CountryService _countryService;

        public StudentsController(StudentsService studentsService
            , CountryService countryService)
        {
            this._studentsService = studentsService;
            this._countryService = countryService;
        }

        // GET: Student
        public async Task<ActionResult> Index(int pageNo = 1, string name = "")
        {
            var pageSize = 5;
            var model = new StudentsHomeModel
            {
                PageNo = pageNo,
                Name = name,
                Students = _studentsService.GetPage(pageNo, pageSize, name),
                // Countries = (await _countryService.GetCountries()).ToList()
            };


            model.Countries = await Task.Run(() =>
            {
                return _countryService.GetCountries().ToList();
            });

            if (model.Students.Count() == 0)
                model.PageNo = 1;
            return View(model);
        }

        // GET: Student/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            var studentVM = new StudentViewModel
            {
                Countries = _countryService.GetCountries()
            };
            return View(studentVM);
        }

        // POST: Student/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Student student)
        {
            try
            {
                _studentsService.Create(student);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _studentsService.Get(id);
            return View(model);
        }

        // GET: Student/Deactivate/5
        public ActionResult Deactivate(int id)
        {
            _studentsService.Deactivate(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: Student/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Student student)
        {
            try
            {
                _studentsService.Update(id, student);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            _studentsService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

StudentRegistration.Web/Views/Shared/_CreateStudentPartial.cshtml
@model StudentRegistration.Web.Entities.Student
@using StudentRegistration.Web.Entities
@{
    var Countries = (List<Country>)ViewData["Countries"];
}
<form method="post" asp-action="Create" asp-controller="Students" class="form">
    <div id="createModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5>
                        Create Students
                    </h5>
                </div>
                <div class="modal-body">

                    <div class="row">
                        <div class="form-group col-6">
                            <label class="control-label" asp-for="Name"></label>
                            <input class="form-control" asp-for="Name" />
                        </div>
                        <div class="form-group col-6">
                            <label class="control-label" asp-for="CountryId"></label>
                            <select asp-for="CountryId" onchange="CountryChanged()">
                                @foreach (var country in Countries)
                                {
                                    <option>
                                        @country.Name
                                    </option>
                                }
                            </select>
                        </div>
                        <div class="form-group col-6">
                            <label class="control-label" asp-for="NationalId"></label>
                            <input class="form-control" asp-for="NationalId" />
                        </div>
                        <div class="form-group col-6">
                            <label class="control-label" asp-for="DateOfBirth"></label>
                            <input class="form-control" asp-for="DateOfBirth" />
                        </div>
                        <div class="form-group col-6">
                            <label class="control-label" asp-for="Email"></label>
                            <input class="form-control" asp-for="Email" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group col-4">
                            <button type="submit">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

StudentRegistration.Web/Views/Shared/_DeleteStudentPartial.cshtml
<form method="post" class="form-row">
    <div id="deleteModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Alert</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        Are you sure you want to delete ?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" onclick="deleteStudent(); return false;">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>

<script>
    var idToDelete = 0;
    function deleteStudent() {
        $.ajax({
            method: 'delete',
            url: `/api/studentsapi/${idToDelete}`,
            success: function (e) {
                alert('student deleted');
                $("#deleteModal").modal('toggle');
                idToDelete = 0;
                getStudents();
            },
            error: function (e) {
                alert('error');
            }
        });
    }
    function confirmDelete(id) {
        idToDelete = id;
        $("#deleteModal").modal('show');
    }
    function getStudents() {
        $.ajax({
            method: 'get',
            url: `/api/studentsapi`,
            success: function (e) {
                console.log(e);
            },
            error: function (e) {
                alert('error');
            }
        });
    }
</script>

StudentRegistration.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentRegistration.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header id="Top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentRegistration.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - StudentRegistration.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            |
            <a asp-fragment="Top">Go To Top</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>